### ISSUE TITLE
'become' is not a valid attribute for a TaskInclude

### ISSUE THREAD

**Issue by bbaassssiiee** [devoperate/ansible-gpg#1]
ansible 2.8.0

ERROR! 'become' is not a valid attribute for a TaskInclude

The error appears to be in 'roles/devoperate.gpg/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Include appropriate task for target host's OS
  ^ here

**Comment by claudeleveille** [comment]
This was patched in v0.1.3, everything from me that depended on this was also patched to depend on the new version.

What version are you using?

**Comment by bbaassssiiee** [comment]
It is OK now.
